---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

https://www.r-bloggers.com/trend-forecasting-models-and-seasonality-with-time-series/

```{r}
setwd("/Users/Emmanuel/Desktop/ptut")

library(xlsx)
library(xts)
library(tidyverse)

```

```{r}

datdon=read.xlsx("/Users/Emmanuel/Desktop/ptut/essais1.xlsx", sheetIndex=1, header=TRUE, colClasses=NA)

```



```{r, echo=TRUE}
#exponential trend model
exp.model <- lm(log(O3)~minutes,data = datdon) 
exp.model.df <- data.frame(x=datdon$minutes,
                           y=exp(fitted(exp.model)))
```

```{r, echo=TRUE}
ggplot(datdon, aes(x = minutes, y = O3)) + geom_point() +
  stat_smooth(method = 'lm', aes(colour = 'linear'), se = FALSE) +
  stat_smooth(method = 'lm', formula = y ~ poly(x,2), aes(colour = 'quadratic'), se= FALSE) +
  stat_smooth(method = 'lm', formula = y ~ poly(x,3), aes(colour = 'cubic'), se = FALSE)+stat_smooth(data=exp.model.df, method = 'loess',aes(x,y,colour = 'exponential'), se = FALSE)+labs(y="réponse en tension du capteur mq131 (micro-Volts)")
```

```{r, echo=TRUE}
model_linear <- lm(data = datdon,O3~minutes)

```

```{r, echo=TRUE}
adj_r_squared_linear <- summary(model_linear) %>% 
  .$adj.r.squared %>% 
  round(4)
```

```{r, echo=TRUE}
model_exponential <- lm(data = datdon,log(O3)~temps)
```

```{r, echo=TRUE}
summary(model_exponential)

```

```{r, echo=TRUE}
library(purrr)

```

```{r, echo=TRUE}
y_predicted <- model_exponential$fitted.values %>% 
  map_dbl(~exp(.+0.09939^2/2))
```

```{r, echo=TRUE}
r_squared_exponential <- (cor(y_predicted,datdon$O3))^2
```

```{r, echo=TRUE}
adj_r_squared_exponential <- 1-(1-r_squared_exponential)*
  ((nrow(datdon)-1)/(nrow(datdon)-1-1))
```

#Model variables

```{r, echo=TRUE}
model_quadratic <- lm(data = datdon,O3~poly(minutes,2))
model_cubic <- lm(data = datdon,O3~poly(minutes,3))
```

#adjusted coefficients of determination

```{r, echo=TRUE}
adj_r_squared_quadratic <- summary(model_quadratic) %>% 
  .$adj.r.squared
```

```{r, echo=TRUE}
adj_r_squared_cubic <- summary(model_cubic) %>% 
  .$adj.r.squared
```

```{r, echo=TRUE}
adj_r_squared_all <- c(linear=round(adj_r_squared_linear,4),
                   exponential=round(adj_r_squared_exponential,4),
                   quadratic=round(adj_r_squared_quadratic,4),
                   cubic=round(adj_r_squared_cubic,4))                     
```

```{r, echo=TRUE}
adj_r_squared_all

```


